#define PUNTO_COMA 0
#define EPSILON 1
#define PALABRA_RESERVADA 2
#define ID 3
#define FUNCION 4
#define PARENTESIS_ABRE 5
#define PARENTESIS_CIERRA 6
#define LLAVE_ABRE 7
#define LLAVE_CIERRA 8
#define COMA 9
#define SI 10
#define SINO 11
#define MIENTRAS 12
#define IGUAL 13
#define MAS 14
#define MENOS 15
#define POR 16
#define ENTRE 17
#define NUMERO 18
#define MENOR 19
#define MAYOR 20
#define MAYOR_IGUAL 21
#define MENOR_IGUAL 22
#define DISTINTO 23
#define IDENTICO 24